config/routes.rb
Saveitforthehoneymoon::Application.routes.draw do

  match 'todays_deal'=>'deals#show', :as=>:todays_deal

  resources :merchants do
    resources :deals, controller:'merchants_deals'
  end

  resources :deals

  resources :consumers do
    resources :purchased_deals#, only:[:show, :index]
  end

  resource  :session, :controller => 'sessions', :only => [:create]

  match 'purchased_deals/:id/image'=>'purchased_deals#image'
  match 'purchased_deals/thanks_for_purchasing'=>'purchased_deals#thanks_for_purchasing' #temp route/action untill billing code is complete
  match 'purchased_deals/redeem'=>'purchased_deals#redeem', :via=>:put, as:'redeem_purchased_deal'
  resources :purchased_deals

   root :to => "deals#show"

end

app/models/consumer.rb
class Consumer < ActiveRecord::Base
  has_one :user, :as=>:authenticateable
  accepts_nested_attributes_for :user

  has_many :purchased_deals
  has_many :deals, :through=>:purchased_deals

  validates :user, presence:true

end

app/controllers/consumers_controller.rb
class ConsumersController < ApplicationController


  def index
    @consumers = Consumer.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @consumers }
    end
  end


  def setup
    @consumer.build_user if @consumer.user.nil?
    @years = (Time.now.year..Time.now.year + 3).map {|y| [y,y] }
    @months = (1..12).map {|m| [Date::MONTHNAMES[m], m]}
  end


  def show
    @consumer = Consumer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @consumer }
    end
  end



  def new
    @consumer = Consumer.new
    setup

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @consumer }
    end
  end


  def edit
    @consumer = Consumer.find(params[:id])
  end



  def create
    @consumer = Consumer.new(params[:consumer])

    respond_to do |format|
      if @consumer.save
        flash[:notice] = "You're All Set.  Look For Our Emails"
        format.html { redirect_to(:back) }
        format.xml  { render :xml => @consumer, :status => :created, :location => @consumer }
        format.js  { render action:'success'}
      else
        setup
        format.html { render :action => "new", :status => :unprocessable_entity}
        format.xml  { render :xml => @consumer.errors, :status => :unprocessable_entity }
        #format.js  { render action:'failure', :status => :unprocessable_entity}
      end
    end
  end



  def update
    @consumer = Consumer.find(params[:id])

    respond_to do |format|
      if @consumer.update_attributes(params[:consumer])
        format.html { redirect_to(@consumer, :notice => 'Consumer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @consumer.errors, :status => :unprocessable_entity }
      end
    end
  end



  def destroy
    @consumer = Consumer.find(params[:id])
    @consumer.destroy

    respond_to do |format|
      format.html { redirect_to(consumers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/consumers_helper.rb
module ConsumersHelper
end

app/views/consumers/_form.html.erb
<%= form_for(@consumer, html:{class:"inline", remote:true}) do |f| %>

  <%= f.fields_for :user do |f|%>
    <div class="field inline">
      <!--<%= f.label :email %><br />-->
      <%= f.text_field :email, :type => "email", placeholder:"Your Email Address" %>
    </div>
    <br />
    <div class="field hide-until-email inline">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
  <% end %>

  <div name="wedding-date" class="field hide-until-email inline">
    <%= f.label "When's Your Wedding?" %><br />
    <div class="field inline tabbed">
      <%= f.select :wedding_month, @months  %>
    </div>
    <div class="field inline">
      <%= f.select :wedding_year, @years  %>
    </div>
  </div>

  <div class="field inline hide-until-email">
    <%= f.label :postal_code %><br />
    <%= f.text_field :postal_code %>
  </div>

  <div class="actions inline hide-until-email">
    <%= f.submit "Send Me The Deals!" %>
  </div>

  <% if @consumer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@consumer.errors.count, "error") %> prohibited this consumer from being saved:</h2>

      <ul>
      <% @consumer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

<script type="text/javascript">
  $(".hide-until-email").hide();
  $("input[name*='email']").focus(function(){
    $(".hide-until-email").slideDown();
  });
</script>

app/views/consumers/edit.html.erb
<h1>Editing consumer</h1>

<%= render 'form' %>

<%= link_to 'Show', @consumer %> |
<%= link_to 'Back', consumers_path %>

app/views/consumers/index.html.erb
<h1>Listing consumers</h1>

<table>
  <tr>
    <th>Wedding month</th>
    <th>Wedding year</th>
    <th>Postal code</th>
    <th>Authenticateable</th>
    <th>Authenticateable type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @consumers.each do |consumer| %>
  <tr>
    <td><%= consumer.wedding_month %></td>
    <td><%= consumer.wedding_year %></td>
    <td><%= consumer.postal_code %></td>
    <td><%= consumer.authenticateable_id %></td>
    <td><%= consumer.authenticateable_type %></td>
    <td><%= link_to 'Show', consumer %></td>
    <td><%= link_to 'Edit', edit_consumer_path(consumer) %></td>
    <td><%= link_to 'Destroy', consumer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Consumer', new_consumer_path %>

app/views/consumers/new.html.erb
<h1>New consumer</h1>

<%= render 'form' %>

<%= link_to 'Back', consumers_path %>

app/views/consumers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Wedding month:</b>
  <%= @consumer.wedding_month %>
</p>

<p>
  <b>Wedding year:</b>
  <%= @consumer.wedding_year %>
</p>

<p>
  <b>Postal code:</b>
  <%= @consumer.postal_code %>
</p>

<p>
  <b>Authenticateable:</b>
  <%= @consumer.authenticateable_id %>
</p>

<p>
  <b>Authenticateable type:</b>
  <%= @consumer.authenticateable_type %>
</p>


<%= link_to 'Edit', edit_consumer_path(@consumer) %> |
<%= link_to 'Back', consumers_path %>

app/views/consumers/success.js.erb
<%= render 'application/flash_update' %>
$('#new_user_signup').hide();