config/routes.rb
Saveitforthehoneymoon::Application.routes.draw do

  match 'todays_deal'=>'deals#show', :as=>:todays_deal

  resources :merchants do
    resources :deals, controller:'merchants_deals'
  end

  resources :deals

  resources :consumers do
    resources :purchased_deals#, only:[:show, :index]
  end

  resource  :session, :controller => 'sessions', :only => [:create]

  match 'purchased_deals/:id/image'=>'purchased_deals#image'
  match 'purchased_deals/thanks_for_purchasing'=>'purchased_deals#thanks_for_purchasing' #temp route/action untill billing code is complete
  match 'purchased_deals/redeem'=>'purchased_deals#redeem', :via=>:put, as:'redeem_purchased_deal'
  resources :purchased_deals

   root :to => "deals#show"

end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
  has_one :user, :as=>:authenticateable
  has_many :deals
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  # GET /merchants
  # GET /merchants.xml
  def index
    @merchants = Merchant.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @merchants }
    end
  end

  # GET /merchants/1
  # GET /merchants/1.xml
  def show
    @merchant = Merchant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @merchant }
    end
  end

  # GET /merchants/new
  # GET /merchants/new.xml
  def new
    @merchant = Merchant.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @merchant }
    end
  end

  # GET /merchants/1/edit
  def edit
    @merchant = Merchant.find(params[:id])
  end

  # POST /merchants
  # POST /merchants.xml
  def create
    @merchant = Merchant.new(params[:merchant])

    respond_to do |format|
      if @merchant.save
        format.html { redirect_to(@merchant, :notice => 'Merchant was successfully created.') }
        format.xml  { render :xml => @merchant, :status => :created, :location => @merchant }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @merchant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /merchants/1
  # PUT /merchants/1.xml
  def update
    @merchant = Merchant.find(params[:id])

    respond_to do |format|
      if @merchant.update_attributes(params[:merchant])
        format.html { redirect_to(@merchant, :notice => 'Merchant was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @merchant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /merchants/1
  # DELETE /merchants/1.xml
  def destroy
    @merchant = Merchant.find(params[:id])
    @merchant.destroy

    respond_to do |format|
      format.html { redirect_to(merchants_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/_form.html.erb
<%= form_for(@merchant) do |f| %>
  <% if @merchant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@merchant.errors.count, "error") %> prohibited this merchant from being saved:</h2>

      <ul>
      <% @merchant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :contact_name %><br />
    <%= f.text_field :contact_name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :authenticateable_id %><br />
    <%= f.text_field :authenticateable_id %>
  </div>
  <div class="field">
    <%= f.label :authenticateable_type %><br />
    <%= f.text_field :authenticateable_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/merchants/edit.html.erb
<h1>Editing merchant</h1>

<%= render 'form' %>

<%= link_to 'Show', @merchant %> |
<%= link_to 'Back', merchants_path %>

app/views/merchants/index.html.erb
<h1>Listing merchants</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Contact name</th>
    <th>Address</th>
    <th>Authenticateable</th>
    <th>Authenticateable type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @merchants.each do |merchant| %>
  <tr>
    <td><%= merchant.name %></td>
    <td><%= merchant.email %></td>
    <td><%= merchant.phone %></td>
    <td><%= merchant.contact_name %></td>
    <td><%= merchant.address %></td>
    <td><%= merchant.authenticateable_id %></td>
    <td><%= merchant.authenticateable_type %></td>
    <td><%= link_to 'Show', merchant %></td>
    <td><%= link_to 'Edit', edit_merchant_path(merchant) %></td>
    <td><%= link_to 'Destroy', merchant, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Merchant', new_merchant_path %>

app/views/merchants/new.html.erb
<div class='section'>
<div class='section'>
  <h1>New merchant</h1>
  <%= render 'form' %>
  <%= link_to 'Back', merchants_path %>
</div>
</div>

app/views/merchants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @merchant.name %>
</p>

<p>
  <b>Email:</b>
  <%= @merchant.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @merchant.phone %>
</p>

<p>
  <b>Contact name:</b>
  <%= @merchant.contact_name %>
</p>

<p>
  <b>Address:</b>
  <%= @merchant.address %>
</p>

<p>
  <b>Authenticateable:</b>
  <%= @merchant.authenticateable_id %>
</p>

<p>
  <b>Authenticateable type:</b>
  <%= @merchant.authenticateable_type %>
</p>


<%= link_to 'Edit', edit_merchant_path(@merchant) %> |
<%= link_to 'Back', merchants_path %>