config/routes.rb
Saveitforthehoneymoon::Application.routes.draw do

  match 'todays_deal'=>'deals#show', :as=>:todays_deal

  resources :merchants do
    resources :deals, controller:'merchants_deals'
  end

  resources :deals

  resources :consumers do
    resources :purchased_deals#, only:[:show, :index]
  end

  resource  :session, :controller => 'sessions', :only => [:create]

  match 'purchased_deals/:id/image'=>'purchased_deals#image'
  match 'purchased_deals/thanks_for_purchasing'=>'purchased_deals#thanks_for_purchasing' #temp route/action untill billing code is complete
  match 'purchased_deals/redeem'=>'purchased_deals#redeem', :via=>:put, as:'redeem_purchased_deal'
  resources :purchased_deals

   root :to => "deals#show"

end

app/models/deal.rb
class Deal < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_many :purchased_deals
  has_many :consumers, :through=>:purchased_deals
  belongs_to :merchant



  validates :copy, presence:true
  validates :copy_header, presence:true
  validates :copy_subheader, presence:true
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_filter only:[:show] {|controller| @allow_new_users = true}

  def index
    @deals = Deal.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @deals }
    end
  end



  def show

    #TODO: update Deal.last to show today's deal
    params[:id].nil? ? @deal = Deal.last : @deal = Deal.find(params[:id])
    @consumer = Consumer.new 
    @consumer.build_user
    @years = (Time.now.year..Time.now.year + 3).map {|y| [y,y] }
    @months = (1..12).map {|m| [Date::MONTHNAMES[m], m]}


    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @deal }
    end
  end



  def new
    @deal = Deal.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @deal }
    end
  end


  def edit
    @deal = Deal.find(params[:id])
  end



  def create
    @deal = Deal.new(params[:deal])

    respond_to do |format|
      if @deal.save
        format.html { redirect_to(@deal, :notice => 'Deal was successfully created.') }
        format.xml  { render :xml => @deal, :status => :created, :location => @deal }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @deal.errors, :status => :unprocessable_entity }
      end
    end
  end



  def update
    @deal = Deal.find(params[:id])

    respond_to do |format|
      if @deal.update_attributes(params[:deal])
        format.html { redirect_to(@deal, :notice => 'Deal was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @deal.errors, :status => :unprocessable_entity }
      end
    end
  end



  def destroy
    @deal = Deal.find(params[:id])
    @deal.destroy

    respond_to do |format|
      format.html { redirect_to(deals_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_deal_picture.html.erb
<dl class='polaroid pull-right'>
  <dd>
     <%=image_tag deal.image.url(:medium) %>
  </dd>
  <dt>
    some caption text
  </dt>
</dl>

app/views/deals/_form.html.erb
<%= form_for(@deal, html:{multipart:true}) do |f| %>
  <% if @deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
      <% @deal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :live_at %><br />
    <%= f.datetime_select :live_at %>
  </div>
  <div class="field">
    <%= f.label :merchant_id %><br />
    <%= f.text_field :merchant_id %>
  </div>
  <div class="field">
    <%= f.label :copy_header %><br />
    <%= f.text_area :copy_header %>
  </div>
  <div class="field">
    <%= f.label :copy_subheader %><br />
    <%= f.text_area :copy_subheader %>
  </div>
  <div class="field">
    <%= f.label :copy %><br />
    <%= f.text_area :copy %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deals/edit.html.erb
<h1>Editing deal</h1>

<%= render 'form' %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

app/views/deals/index.html.erb
<h1>Listing deals</h1>

<table>
  <tr>
    <th>Live at</th>
    <th>Merchant</th>
    <th>Copy</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @deals.each do |deal| %>
  <tr>
    <td><%= deal.live_at %></td>
    <td><%= deal.merchant_id %></td>
    <td><%= deal.copy %></td>
    <td><%= link_to 'Show', deal %></td>
    <td><%= link_to 'Edit', edit_deal_path(deal) %></td>
    <td><%= link_to 'Destroy', deal, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Deal', new_deal_path %>

app/views/deals/new.html.erb
<div class='section'>
  <div class='section'>
  <h1>New deal</h1>

  <%= render 'form' %>

  <%= link_to 'Back', deals_path %>
  </div>
</div>

app/views/deals/show.html.erb
<div class='section'>
   <%= image_tag 'clip.png', style:'position:absolute; z-index:1; height:100px; top:-18px; left:-36px;'  %>
  <%= render 'deals/deal_picture', deal:@deal%>

  <div class='section'>
    <%= button_to "Buy It!", purchased_deals_path("purchased_deal[deal_id]"=>@deal.id), class:'buy-it' %>
    <div class='deal-headline'>
      <h1><%= @deal.copy_header.html_safe %></h1>
      <h2><%= @deal.copy_subheader.html_safe %></h2>
      <div><%= @deal.copy.html_safe %></div>
    </div>
  </div>
</div>