config/routes.rb
Saveitforthehoneymoon::Application.routes.draw do

  match 'todays_deal'=>'deals#show', :as=>:todays_deal

  resources :merchants do
    resources :deals, controller:'merchants_deals'
  end

  resources :deals

  resources :consumers do
    resources :purchased_deals#, only:[:show, :index]
  end

  resource  :session, :controller => 'sessions', :only => [:create]

  match 'purchased_deals/:id/image'=>'purchased_deals#image'
  match 'purchased_deals/thanks_for_purchasing'=>'purchased_deals#thanks_for_purchasing' #temp route/action untill billing code is complete
  match 'purchased_deals/redeem'=>'purchased_deals#redeem', :via=>:put, as:'redeem_purchased_deal'
  resources :purchased_deals

   root :to => "deals#show"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Authentication
  protect_from_forgery
  after_filter :no_xhr_flashes

  def no_xhr_flashes
    flash.discard if request.xhr?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash_update.js.erb
var $new_flashes = $("<% flash.each do |key, value| -%><div class='flash section <%= key %>'><%=h value %></div><% end -%>"); 
$('.flash').last().after($new_flashes);
$new_flashes.hide();
$new_flashes.show('slide', {direction: 'right'}, 500);

app/views/application/_footer.html.erb
<div id='footer-container'>
  <div id='footer'>A Dapple Before Dawn Production, Copyright 2011 </div> 
  <%= image_tag 'dapplebeforedawn_logo.png', class:'dapple-logo' %>
</div>

<script type="text/javascript">
  jQuery(function($){
    $('#footer').addClass('footer-hide');
    $('.dapple-logo').hover(function(e){
      $('#footer').addClass('footer-show');
      $('#footer').removeClass('footer-hide');
    }, function(e){
      $('#footer').removeClass('footer-show');
      $('#footer').addClass('footer-hide');
    });
  });
</script>

app/views/application/_header.html.erb
<div id='header' class='section'>
  <%= link_to root_url, style:'text-decoration:none;' do %>
    <h1>Save It For The Honeymoon!</h1>
  <% end %>
  <span class='tag-line'>Your destination for wedding savings.</span>

  <ul id='site-menu' class='linear'>
    <!--<li><%= link_to_unless_current 'For Brides', '#' %></li>
    <li><%= link_to 'For Merchants', '#' %></li>-->
    <% unless current_user.nil? %>
      <li>
        <span>Hi, </span> 
        <strong><%= current_user.name_from_email %></strong>
        <span class='small'> - Not you? </span>
        <%= link_to "Sign out", sign_out_path, :method=>:delete, class:'small' %>
      </li>
      <li>
        <%= link_to "My Stuff", consumer_purchased_deals_path(current_user.consumer) %>
      </li>
    <% end %>
  </ul>
</div>

app/views/application/_signin.html.erb
<div class='section' id='signin'>
<div class='section'>
<h2>Sign In: </h2>
  <%= render 'sessions/form' %>
<ul>
  <li>
    <%= link_to "Forgot password?", new_password_path %>
  </li>
</ul>
</div>
</div>

<script type="text/javascript">
  $("#signin").hide();
  $('[href="#signin"]').click(function(e){
    e.preventDefault();
    $('#new_user_signup').hide();
    $("#signin").slideDown();
  });
</script>

app/views/application/_ui_error.html.erb
<div class="ui-state-error ui-corner-all ui-widget ui-notification">
  <span class="ui-icon ui-icon-alert"></span>
  <strong><%= text %></strong>
</div>